version: '3.9'
services:
  sso:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sso
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
    ports:
      - "44044:44044"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
