version: "3"

tasks:
  # App
  run:local:
    desc: "Run app with local config"
    cmds:
      - go run ./cmd/sso --config=./config/local.yaml
  run:test:
    desc: "Run app with test config"
    cmds:
      - go run ./cmd/sso --config=./config/local_tests_config.yaml
  # Migrations
  migrate:local:
    desc: "Migrate main database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  migrate:test:
    desc: "Migrate test database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  # Test
  test:
    desc: "Run migrations, and then run tests"
    cmds:
      - go test ./tests -count=1 -v